/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/races/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Races Today */
        get: operations["races_today_races_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/races/{race_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Race */
        get: operations["race_races__race_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/performance/oos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Oos */
        get: operations["oos_performance_oos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/performance/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_performance_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/races/{race_id}/betslip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Betslip Text
         * @description WB-08 相当: 楽天競馬/SPAT4 形式のコピー用テキストを返す。
         *
         *     金額・馬番は `race` callable が返す確定済みの推奨（stake_yen）から作る。
         *     フォーマットは discord.betslip の単一実装をそのまま呼び、TS 側では
         *     再実装しない（設計書 §5.1 の要件）。
         */
        get: operations["betslip_text_races__race_id__betslip_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Models */
        get: operations["models_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{release_id}/promote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Promote Model
         * @description WB-06: 昇格は admin のみ・二段確認必須。判定は release.py の既存ゲートを使う。
         */
        post: operations["promote_model_models__release_id__promote_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DailyPnL */
        DailyPnL: {
            /**
             * Business Date
             * Format: date
             */
            business_date: string;
            /** N Races */
            n_races: number;
            /** N Bets */
            n_bets: number;
            /** Stake Yen */
            stake_yen: number;
            /** Return Yen */
            return_yen: number;
            /** Roi */
            roi: number;
            /** Hit Rate */
            hit_rate: number;
            /** Is Paper */
            is_paper: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HorsePrediction */
        HorsePrediction: {
            /** Horse No */
            horse_no: number;
            /** Horse Name */
            horse_name?: string | null;
            /** P Win */
            p_win: number;
            /** P Market */
            p_market?: number | null;
            /** Ev */
            ev?: number | null;
            /** Ev Adjusted */
            ev_adjusted?: number | null;
            /** Stake Yen */
            stake_yen: number;
        };
        /**
         * ModelRelease
         * @description `/models` 画面向け。gs://nar-model/releases/<id>/manifest.json を要約する。
         */
        ModelRelease: {
            /** Release Id */
            release_id: string;
            /** Is Current */
            is_current: boolean;
            /** Model Id */
            model_id: string;
            /** Dataset Version */
            dataset_version: string;
            /**
             * Train Period Start
             * Format: date
             */
            train_period_start: string;
            /**
             * Train Period End
             * Format: date
             */
            train_period_end: string;
            /** Git Commit */
            git_commit: string;
            /**
             * Track
             * @enum {string}
             */
            track: "A" | "B";
            /** Purpose */
            purpose: string;
            /** Oos Metrics */
            oos_metrics: {
                [key: string]: number;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * OOSMetrics
         * @description 保存済み評価テーブル由来。オンザフライ再計算はしない（WB-03）。
         */
        OOSMetrics: {
            /** Model */
            model: string;
            /**
             * Track
             * @enum {string}
             */
            track: "A" | "B";
            /** Race Nll */
            race_nll: number;
            /** Top1 */
            top1: number;
            /** Top3 */
            top3?: number | null;
            /** Brier */
            brier?: number | null;
            /** Ece */
            ece: number;
            /**
             * Evaluated At
             * Format: date-time
             */
            evaluated_at: string;
            /**
             * Source
             * @default stored
             * @constant
             */
            source: "stored";
        };
        /** PromoteRequest */
        PromoteRequest: {
            /**
             * Confirmed
             * @default false
             */
            confirmed: boolean;
        };
        /** RacePrediction */
        RacePrediction: {
            /** Race Id */
            race_id: string;
            /**
             * Race Date
             * Format: date
             */
            race_date: string;
            /**
             * Start Ts
             * Format: date-time
             */
            start_ts: string;
            /** Track Name */
            track_name: string;
            /** Race No */
            race_no: number;
            /** Model Release */
            model_release: string;
            /**
             * Track Used
             * @enum {string}
             */
            track_used: "A" | "A+B";
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "insufficient_data" | "expired" | "not_computed";
            /** Horses */
            horses?: components["schemas"]["HorsePrediction"][];
            /**
             * Is Paper
             * @default true
             */
            is_paper: boolean;
        };
        /** SystemHealth */
        SystemHealth: {
            /** Db Watermark */
            db_watermark: string | null;
            /** Model Release */
            model_release: string | null;
            /** Model Trained On */
            model_trained_on: string | null;
            /**
             * Skew Verdict
             * @enum {string}
             */
            skew_verdict: "PASS" | "FAIL" | "UNKNOWN";
            /** Coverage Today */
            coverage_today: number;
            /** Delivery Blocked */
            delivery_blocked: boolean;
            /** Blocked Reason */
            blocked_reason?: string | null;
        };
        /**
         * TodayRace
         * @description ダッシュボード `/` の本日開催タイムライン向け（設計書 §5.2(1)）。
         */
        TodayRace: {
            /** Race Id */
            race_id: string;
            /** Race No */
            race_no: number;
            /** Track Name */
            track_name: string;
            /**
             * Start Ts
             * Format: date-time
             */
            start_ts: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "insufficient_data" | "expired" | "not_computed";
            /** Top Ev Adjusted */
            top_ev_adjusted?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemHealth"];
                };
            };
        };
    };
    races_today_races_today_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodayRace"][];
                };
            };
        };
    };
    race_races__race_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                race_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RacePrediction"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    oos_performance_oos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OOSMetrics"][];
                };
            };
        };
    };
    live_performance_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyPnL"][];
                };
            };
        };
    };
    betslip_text_races__race_id__betslip_get: {
        parameters: {
            query?: {
                site?: "rakuten" | "spat4";
            };
            header?: never;
            path: {
                race_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    models_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelRelease"][];
                };
            };
        };
    };
    promote_model_models__release_id__promote_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                release_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromoteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
